# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Movie's title")),
                ('year', models.PositiveIntegerField(default=2019)),
                ('rated', models.CharField(max_length=64)),
                ('released_on', models.DateField(verbose_name='Release Date')),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('plot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
