# Generated by Django 3.0.7 on 2020-08-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
