# Generated by Django 3.0.7 on 2020-08-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rating_rating_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='votes',
        ),
    ]
